### ISSUE TITLE
отладка сайтов из ext_www

### ISSUE THREAD

**Issue by CaWeb007** [VictorKrasnov/bitrix-env#2]
Было бы очень круто, если бы Вы помогли понять процесс работы нескольких сайтов на данном решении. Я пока новичок в docker. Хочется понять как можно организовать работу не только с одним сайтом. В идеале конечно хочется получить полностью рабочий образ с сайтом(сайтами). По моему печальному опыту, когда ставишь сайты через add_site.sh, делаешь запись в hosts файле рабочей машины(типа 192,168,220,2 site.local), то потом IDE не подхватывает XDEBUG как бы я не крутил. И что если я хочу после например переустановки винды, быстро поднять рабочую локальную среду разработки со своими сайтами? Знаю что гит может автоматом пересобирать образ на docker-hub, только получается нужно всю виртуалку держать под контролем версий что ли. В общем вопросов много. Буду признателен если поможете советом, основанном на опыте. Спасибо)

**Comment by VictorKrasnov** [comment]
1. Про сайты. Этот вопрос вряд ли имеет отношение к докеру. Вот документация по Bitrix Environment про сайты: https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=37&CHAPTER_ID=08847&LESSON_PATH=3908.8809.8847
2. Про переустановку винды. Про винду вообще не могу подсказать, 11 лет назад с нее ушел. На маке есть проблемы c x-debug, но мы их решили, описано в Readme как делать. А, например, в Ubuntu все проще - там можно IP адрес указывать внутренней сети докера. В нашем случае это всегда 192.168.220.1. А в целом главное сохранить папку, куда все ставили, все настройки нужные для поднятия на другой машине вынесены из контейнера на хост-машину, правда придется подождать, пока поставится Bitrix environment. Это же произойдет - если нечаянно дропнуть контейнер. Собственно, эта проблема в решениях других разработчиков и послужила необходимостью сделать свою сборку.
